sarax_mani:
  # Publish all joint states -----------------------------------
  sarax_mani_joint_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 150

  # Effort Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: mani_joint_1
    pid: {p: 1.0, i: 0, d: 0}
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: mani_joint_2
    pid: {p: 1.0, i: 0, d: 0}
